### ISSUE TITLE
On login screen, write "Email" instead of "Username" to login name field.

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2DROP/b2drop-theme#11]
This was already implemented some time ago, but went away for unknown reason.

**Comment by bne86** [comment]
![screen shot 2016-06-29 at 10 04 22](https://cloud.githubusercontent.com/assets/5327850/16444948/df24d976-3de0-11e6-91d6-3525098848db.png)
There fix Username with Email

**Comment by thijscobben** [comment]
overwrite core OwnCloud php cloud

**Comment by thijscobben** [comment]
Ready for testing
