### ISSUE TITLE
Nextcloud 12.x compatibility issues

### ISSUE THREAD

**Issue by hashmich** [EUDAT-B2DROP/b2drop-theme#32]
The current head version does not reflect the CSS file renaming of the NC 12.x branch. 
The file styles.css needs to be renamed to server.css

**Comment by apw1388** [comment]
Dear @hashmich,
thanks for your report. Do you have any problems with the theme? On our instances, even with latest Nextcloud 12 version, everything is fine.

**Comment by hashmich** [comment]
Yes indeed. I was using NC version 12.0.4, as it is indicated on the bottom of https://b2drop.eudat.eu/settings/personal. 
After cloning the theme into the NC themes folder and activating it in the config file, the css file obviously failed to load. Though, some changed menu items indicated, that the theme has been recognized. 
The example theme that is shipped with the NC software has the css file renamed. After renaming the file in the b2drop theme as well, everything was fine. 
Possibly, later NC versions have some kind of backwards compatibility?

**Comment by apw1388** [comment]
Can you provide a screenshot. We are not able to reproduce the problem with different servers.

**Comment by hashmich** [comment]
![missing-b2drop-theme-styles](https://user-images.githubusercontent.com/178177/38624824-54246218-3da9-11e8-8946-32890cbeb33a.png)

**Comment by apw1388** [comment]
Issue is fixed.
