### ISSUE TITLE
Cannot login into b2dropEUDAT //b2acces does not recognize b2dropEUDAT username

### ISSUE THREAD

**Issue by avatar-lavventura** [EUDAT-B2DROP/b2drop-theme#33]
I cannot login into b2drop EUDAT from[ login pag](https://b2drop.eudat.eu/apps/user_saml/saml/selectUserBackEnd?redirectUrl=)e. Old login option is removed and `B2access` does not recognize my user name. Is it possible to activate b2drop's old login page?

**Comment by apw1388** [comment]
No issue of the theme. For issues with the service, the helpdesk should be used.
