### ISSUE TITLE
Adding shared artefacts to own cloud

### ISSUE THREAD

**Issue by TillF** [EUDAT-B2DROP/b2drop-theme#35]
The docu (https://www.eudat.eu/services/userdoc/b2drop#Accessing_shared_artefacts) claims that it is possible to add content shared via link to my own B2DROP home folder. This is indeed a highly desirable feature.

However, the respective dialogue looks differently, and requests credentials, which I do not know. 
![Bildschirmfoto von 2022-05-03 09-48-26](https://user-images.githubusercontent.com/11060560/166420071-514125e5-d06b-4036-9e43-444985446158.png)

**Comment by apw1388** [comment]
Dear TillF,
this would be your federated cloud ID. The documentation needs to be updated. Although most technical stuff is still valid the images should be updated to the new layout. We will inform the documentation team.

**Comment by MelwinQ** [comment]
So adding the shared files to my B2DROP home folder is not / no longer possible? Personally, I would find this more useful than adding them to another cloud service. 
Thanks for relaying the docu issue, though.

**Comment by apw1388** [comment]
It should be possible. It seems that the behaviour of the underlying software has changed. It creates an remote share to itself. It would be more useful to share directly with people on the same system. We will check if there is an issue with this. Nevertheless it is not part of the theme.
