### ISSUE TITLE
Shared via link not showing up correctly with owncloud 8.2

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2DROP/b2drop-theme#6]

**Comment by noumar** [comment]
This is also fixed. @BeneDicere or @apweiler can you confirm and close the issue.

**Comment by bne86** [comment]
I can not confirm this, see screenshot.
<img width="1302" alt="screen shot 2016-01-20 at 15 08 47" src="https://cloud.githubusercontent.com/assets/5327850/12451125/d53d4a60-bf87-11e5-8f60-f8503853a543.png">

**Comment by bne86** [comment]
this is closed in all current branches (owncloud 8.2 and owncloud 9)
