### ISSUE TITLE
reference to eudat user doc

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2DROP/b2drop-theme#7]
there was the question where to get documentation from the service, because FAQ are not enough.
One suggestion was to rename "FAQ" to "HELP" and then we could copy the FAQ over there but add a link to the eudat user doc as the first bullet point.

**Comment by apw1388** [comment]
In B2ACCESS are "User Guide" pointing to documentation at eudat main page and FAQs (located at server itself). Maybe this is a solution for this problem.

**Comment by apw1388** [comment]
Additional link to user doc is available at master, owncloud7, owncloud8.2 and owncloud9.
