### ISSUE TITLE
Notifications button over beehive blocks

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2DROP/b2drop-theme#8]
On 8.2 a white bell can be seen during page load over the beehive blocks, later hidden.
This should probably be moved further down.

**Comment by bne86** [comment]
screenshot please

**Comment by noumar** [comment]
Div can be found by searching `.notifications` in Inspector.

![bell](https://cloud.githubusercontent.com/assets/146694/13809408/5fe2fe64-eb73-11e5-93d7-825bb1e7b531.png)

**Comment by bne86** [comment]
i can't see this in owncloud9, was it for an older version?

**Comment by bne86** [comment]
is this still a issue?

**Comment by bne86** [comment]
fixed with issue #22 and commit 2272d94677741422cbaf42178ff20821e62fc344, 8c34b7591c3bf776890186cb7d3d948850e6a260
